name: rls-med
channels:
  - defaults
  - pytorch
dependencies:
  - pytorch=1.4.0
  - torchvision=0.5.0
  - numpy=1.18.1
  - matplotlib=3.1.3
  - tqdm=4.44.1
  - pip:
    - black==19.10b0
    - flake8==3.7.9
    - pre-commit==1.22.0
    - pylidc==0.2.1
    - pytorch-lightning==0.7.3
    - raster-geometry==0.1.4.1
